### ISSUE TITLE
Not working in IOS

### ISSUE THREAD

**Issue by dungfv** [happones/nativescript-laravel-echo#10]
I am using this plugin with Nativescript-Vue latest. It work fine on Android, but not working for IOS. I cannot connect to socket server, do not have any log.
Even the sample application doesn't work for IOS

**Comment by happones** [comment]
try this:
1.  if your endpoint isn't `https` add 
`<key>NSAppTransportSecurity</key>
        <dict>
            <key>NSAllowsArbitraryLoads</key>
            <true/>
        </dict>
`  into `info.plist`

2. Or try setTimeout

```javascript 
const Echo = new TnsEcho(options);
setTimeout(() => {
    Echo.private('channel');
}, 1000);

**Comment by dungfv** [comment]
Thanks for your help. It worked with setTimeout for my case. 
But why must setTimeout and need setTime for seconds for specific contexts, does it depend on network speed?

**Comment by happones** [comment]
Rather it is a theme of the operating system, the optimal way to invoke Echo would be:
```
<Page @loaded="onLoaded">//Or the component that is GridLayout, etc
</Page>
created() {}, // Not
mounted(){}, // With timeout
methods: {
    onLoaded() {
        const Echo = new TnsEcho(options);
        Echo.private('channel');
    }
}
``` try

**Comment by dungfv** [comment]
I known, thankyou verry much
