### ISSUE TITLE
Receive notifications when App is closed

### ISSUE THREAD

**Issue by emperorjm** [happones/nativescript-laravel-echo#16]
Is there an option to receive notifications even if the app is closed?

**Comment by happones** [comment]
Try push notifications

**Comment by emperorjm** [comment]
The push notification plugin is deprecated and I had to go with the Nativescript firebase plugin (https://github.com/EddyVerbruggen/nativescript-plugin-firebase) using my custom server to generate the messages to get it working but hopefully I will find a solution that works with this plugin as I don't want to be dependent on Firebase.
