### ISSUE TITLE
Connectivity issue

### ISSUE THREAD

**Issue by lord-zeus** [happones/nativescript-laravel-echo#3]
Error: java.lang.SecurityException: ConnectivityService: Neither user 10084 nor current process has android.permission.ACCESS_NETWORK_STATE.

**Comment by happones** [comment]
Try add this into `AndroidManifest.xml` 

```xml
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
 ```

**Comment by lord-zeus** [comment]
> Try add this into `AndroidManifest.xml`
> 
> ```
> <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
> ```

thanks, it works when added directly under the manifest tag
