### ISSUE TITLE
authEndPoint

### ISSUE THREAD

**Issue by lord-zeus** [happones/nativescript-laravel-echo#4]
what is the variable in front of the authEndpoint for ?
`this.Echo = new TnsEcho({`
            `host: this.host,`
           ` authEndpoint: `${this.endpoint}/broadcasting/auth`,`
            `broadcaster: this.broadcast?'pusher':'socket.io',`
            `key: this.key,`
            `debug: false,`
            `auth: {`
                `headers: {`
                 `   'Authorization': this.token`
                `}`
            `}`
        `});`

laravel authEndpoint is just the /broadcast/auth
its from the demo application

**Comment by happones** [comment]
`authEndpoint` use only for `broadcaster` **pusher**, for **socket.io** use `host`
