### ISSUE TITLE
 Join to a presence channel

### ISSUE THREAD

**Issue by gabrieljaime** [happones/nativescript-laravel-echo#8]
Hi, can you help me to Join to a presence channel?

I probe for all ways and always it rejected . I suppose that the request that i receive in laravel dont have the expected format.

I can connect to a public channel without problem.

Can you help me?

**Comment by lord-zeus** [comment]
please share your error message and code.

**Comment by gabrieljaime** [comment]
I dont recibe an error. I get forgiven.  Thanks

**Comment by happones** [comment]
An full example for presence and private channel, with passport and socket.io [LaravelApp](https://github.com/happones/laravel-echo-example) and [NativeScriptApp](https://github.com/happones/laravel-echo-example-app)
